SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `bendrabutis` DEFAULT CHARACTER SET utf8 COLLATE utf8_lithuanian_ci;
USE `bendrabutis`;

DROP TABLE IF EXISTS `washing_machine`;
CREATE TABLE IF NOT EXISTS `washing_machine` (
  `id` varchar(255) COLLATE utf8_lithuanian_ci NOT NULL,
  `title` varchar(255) COLLATE utf8_lithuanian_ci NOT NULL,
  `image_url` varchar(255) COLLATE utf8_lithuanian_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_lithuanian_ci;

INSERT INTO `washing_machine` (`id`, `title`, `image_url`, `created_at`, `updated_at`) VALUES
('1', 'Bloomberg', 'https://www.stuartwestmoreland.co.uk/wp-content/uploads/2018/09/Blomberg-LWF28442G-2.jpg', '2019-03-10 09:04:02', '2019-03-10 09:04:02');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
